name: Demo CI

on:
  push:
    branches: [ "main" ]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run echo
        run: echo "hello firsy job"
  seconds-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Run echo
        run: echo "hello"        
